-- Run this in Supabase SQL Editor

create table reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  query text not null,
  markdown_content text not null,
  logs jsonb,
  sources jsonb
);

-- Note: Disable Row Level Security (RLS) for this table for the demo.
